name: k5-pull-request-notify

on:
  pull_request:
    types: [opened]
    branches: [develop, master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Novo PR em ${{ github.repository }}. {{ github.event.pull_request.head.ref }} --> ${{ github.event.pull_request.base.ref }}"
          description: 'Mais detalhes: ${{ github.event.pull_request.html_url }}'
          color: 0x0000ff
          username: ${{ github.actor }}
          avatar_url: ${{ github.event.pull_request.user.avatar_url }}
          nodetail: true
