name: k5-pull-request-notify

on:
  pull_request:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: '896138492097208350'
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          username: ${{ github.pull_request.user.login }}
          avatar_url: ${{ github.pull_request.user.avatar_url }}
          message: ${{ github.pull_request.html_url }}
