name: k5-sync-branches

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Sync Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Sync master -> develop
          body: Sincronizando commits de master para develop
          branch: master
          base: develop
